### PR TITLE
make gpgsql-password optional

### PR DESCRIPTION
**Pull request by bastelfreak**
At least for postgresql it's not required that the database_user has a password.

### CODE REVIEW

**Comment by ju5t** [comment]
I'm not sure about this PR. I'm leaning towards forcing database passwords as it is more secure. I also understand that flexibility is really useful too. I'd probably introduce a new variable myself which specifically disables the need for it. This would make it really explicit.

**Comment by bastelfreak** [comment]
@ju5t can you take a look again?

**Comment by bastelfreak** [comment]
hi @ju5t , let me know if you're happy with this or want more/other tests.

**Comment by bastelfreak** [comment]
@ju5t can you please take a look again?

**Comment by ju5t** [comment]
Sorry for the delay. Looks good to me thanks!

**Pull request merged**
