### PR TITLE
fix: issue #97 - sqlite parameta for shemata missing, presetting is w…

### PR DESCRIPTION
**Pull request by LooOOooM**
Please merge the fix for "issue #97 - sqlite parameta for shemata missing, presetting is w…".

### CODE REVIEW

**Comment by LooOOooM** [comment]
I dont get it what the error is. can you help?

**Comment by ju5t** [comment]
@LooOOooM sorry for the late reply. I completely missed it. Feel free to tag me in the future!

I'm not really sure about the error. The only thing I can think of is a Ruby dependency got updated. This happens a lot. Perhaps either rspec-puppet or rspec-puppet-facts got updated and breaks some facts we depend on? I honestly wouldn't know.

Does it test OK on your local machine?

**Comment by LooOOooM** [comment]
Hi,
yes on my local maschine all tests and runs fine.

My guess would have been that this error (in CI/test) fails because there was already earlier a merge into the branch develop, and and more CI test has been afterwarth implementet, which just fail for the realy next commit - mine.

**Comment by ju5t** [comment]
CI uses the exact same code as you do locally. I'm rerunning the tests again.

What did surprise me is that you used the same commit message for every commit. That's very uncommon. Would you mind squashing them into a single commit?

**Pull request closed without merging**
