### PR TITLE
Allow postgresql 8 module

### PR DESCRIPTION
**Pull request by saz**
Adds support for postgresql < 9.0.0

### CODE REVIEW

**Comment by ju5t** [comment]
Thanks! Do you happen know why it fails on 6? I'm unable to view the logs.

**Comment by trefzer** [comment]
as soon as #123 is merged, you can rebase and it should pass.

**Comment by saz** [comment]
@ju5t All checks have passed now. A new release with this change included would be awesome!

**Comment by ju5t** [comment]
@saz sorry for the delay; I've released 2.2.2.

**Pull request merged**
