### PR TITLE
Support for FreeBSD platform and minor fixes

### PR DESCRIPTION
**Pull request by olevole**
It would be nice to make the module more versatile to expand the number of distributions.
Tested with: FreeBSD 12.2-RELEASE, FreeBSD 13-ALPHA1

### CODE REVIEW

**Comment by ju5t** [comment]
Thanks! Looks good.

We switched to Github Actions recently and apparently the tests didn't run. I'd like to get that fixed before merging it so we know nothing else broke.

**Comment by ju5t** [comment]
I can't find how on earth I have to fix it so the tests work. I will merge this, the tests will run then. 

If anything breaks, please help 😄

**Comment by ju5t** [comment]
Ok, so this PR wasn't ready. It pretty much destroyed our tests. There was a variable missing and the code didn't follow the standard Puppet style guide. I'm close to fixing everything but should you have other changes in the future, please, please, please test them. Make sure you're not only fixing your use case but also aren't destroying other use cases.

Either way, thanks for the PR! It's still cool to have some support for FreeBSD. I'm not marking it as fully supported yet though because there are no tests for it.

**Comment by olevole** [comment]
> There was a variable missing and the code didn't follow the standard Puppet style guide. 

Sorry i didn't notice regression through lint. Do you see errors through the PDK ?
I plan to use the module extensively, I am interested in contributing it. Thank you.

**Comment by ju5t** [comment]
We're testing with `bundle exec rake test`. I think you can find most of it in the lower end of our README.

It initially errored out on the indentation of some resources you changed, you can see the test results here:
https://github.com/sensson/puppet-powerdns/runs/1753322003?check_suite_focus=true

Once this was fixed, it failed entirely because you didn't include a default for `mysql_backend_package_name `. You did switch some resources over to use this variable, but not a single OS was configured with it. It took me a while to find it, because it failed on completely different resources.

After fixing that too, it failed on the change you made in `sqlite3`. You use `env` to find the binary, but there is a test that checks what command is used, so that test failed too.

**Comment by olevole** [comment]
Got it. thank you. This was not done on purpose, unfortunately, I did not know.

**Comment by ju5t** [comment]
No worries. Still cool to have support for FreeBSD. If you can add some specific tests for FreeBSD that would be great. Note that this PR is merged now, so adding support for it should be done in a new PR.

**Pull request merged**
