### PR TITLE
Add the ability to install pdns and recursor with differents versions

### PR DESCRIPTION
**Pull request by mouchymouchy**

### CODE REVIEW

**Comment by ju5t** [comment]
Sorry for the late reply! Could you have a look at the failing test?

**Comment by mouchymouchy** [comment]
> Sorry for the late reply! Could you have a look at the failing test?

Done @ju5t 
Didn't see the typo :)

**Comment by saz** [comment]
@ju5t This is a backwards-incompatible change and would have better fit into a major version change.

Maybe a note in the CHANGELOG might be good, as it's already released anyways.

**Comment by ju5t** [comment]
@saz Good point. I might just do a major release as it updates the changelog at Puppet Forge too. I usually check changelogs over there instead of GitHub.

**Pull request merged**
