### PR TITLE
Support Debian.

### PR DESCRIPTION
**Pull request by bzed**

### CODE REVIEW

**Comment by bzed** [comment]
(failing tests are not a problem comong from this pull request)

**Comment by sensson** [comment]
Thanks @bzed! 

It turns out rake released a new version which removed support for last_comment entirely. Your tests failed due to that. We don't use it ourselves but other Gems do. I've pushed a new Gemfile which pins rake to a version equal or below 11.3.0 so tests should pass again if you merge the current master branch into your change.

Could you also make the change to metadata.json so tests will run on Debian 8? Without it the code is only tested on Ubuntu and CentOS. The PowerDNS repo only supports Debian 8 at the moment.

It also helps if you could add a nodeset and run a simple Beaker test to see if you don't hit anything that is not so easily covered by spec tests. The current nodesets can be found in https://github.com/sensson/puppet-powerdns/tree/master/spec/acceptance/nodesets.

**Comment by sensson** [comment]
Hi @bzed. I've just added support for Debian 8 including a set of Beaker tests. I'm going to close your pull request in favour of commit https://github.com/sensson/puppet-powerdns/commit/0f054cd5efb787e6bc92c754491e7fbd89088e3a. Thank you very much for bringing it up though, much appreciated!

**Comment by bzed** [comment]
Thanks a lot,  and sorry for not improving my pull request,  Christmas time is always very busy. 

Am 22. Dezember 2016 20:12:05 MEZ, schrieb Sensson <notifications@github.com>:
>Hi @bzed. I've just added support for Debian 8 including a set of
>Beaker tests. I'm going to close your pull request in favour of commit
>https://github.com/sensson/puppet-powerdns/commit/0f054cd5efb787e6bc92c754491e7fbd89088e3a.
>Thank you very much for bringing it up though, much appreciated!
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/sensson/puppet-powerdns/pull/5#issuecomment-268869254

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Pull request closed without merging**
