### PR TITLE
Fix: Issue #97

### PR DESCRIPTION
**Pull request by LooOOooM**
Please merge this, fixing schemes for sqlite on centos 7/8

### CODE REVIEW

**Comment by LooOOooM** [comment]
I am getting teh following error during ci, however I have no clue why this is failing. Any idears what I do wrong ?:

```
2021-03-29T14:56:28.8126004Z Code coverage
2021-03-29T14:56:28.8205729Z   must cover at least 0% of resources
2021-03-29T14:56:28.8206387Z Total resources:   106
2021-03-29T14:56:28.8206808Z Touched resources: 105
2021-03-29T14:56:28.8207245Z Resource coverage: 99.06%
2021-03-29T14:56:28.8207528Z 
2021-03-29T14:56:28.8207881Z Untouched resources:
2021-03-29T14:56:28.8208329Z   Yumrepo[powertools]
2021-03-29T14:56:28.8832135Z /opt/hostedtoolcache/Ruby/2.5.8/x64/bin/ruby -I/home/runner/work/puppet-powerdns/puppet-powerdns/vendor/bundle/ruby/2.5.0/gems/rspec-core-3.10.1/lib:/home/runner/work/puppet-powerdns/puppet-powerdns/vendor/bundle/ruby/2.5.0/gems/rspec-support-3.10.2/lib /home/runner/work/puppet-powerdns/puppet-powerdns/vendor/bundle/ruby/2.5.0/gems/rspec-core-3.10.1/exe/rspec --pattern spec/\{aliases,classes,defines,functions,hosts,integration,plans,tasks,type_aliases,types,unit\}/\*\*/\*_spec.rb failed
2021-03-29T14:56:28.9015278Z ##[error]Process completed with exit code 1.
```

**Comment by ju5t** [comment]
I think the tests in Github didn't run because of a few reasons:

- You set the PR target to `main` instead of `develop`.
- You made your changes in `main` of your own fork instead of a branch.

Neither would trigger a CI run in our configuration, as far as I know.

The output you've shared doesn't explain much to me. I don't know where it's coming from?

Some feedback on your PR:

- Can you reword or squash the initial commits so they all follow semantic commits?
- Can you add a check to see if the schema sql file exists?

I know in an earlier issue you posted the output of what the RPM is supposed to do and the schema file is part of this. But as mentioned there too, the schema isn't actually copied, at least, not when you use any of the official, stable, repositories. You used an alpha build there, but as I hope you can understand, we're not aiming for any alpha support. Only stable releases are supported.

**Comment by ju5t** [comment]
One more remark, would you be able to pick a short but descriptive title instead of `fix: issue #97`? Right now there aren't many PR's, but if you have a list of them it helps if the title has a little bit more to it.

**Comment by LooOOooM** [comment]
Hi Thx for your Help,
I will close that request, as I just started from scratch working on branch develop. I will make another PR from there. 

Thank you regarding the "alpha version" of pdns. By mistake I configured the master-repo rather then the stable version 4.4.

However in Version 4.4 the Schema file is in both version centos 7/8 for pdns 4.4 existing:

```
[root@puppet-centos7-testvm1 ~]# cat /etc/redhat-release; rpm -ql pdns-backend-sqlite|grep \/schema
CentOS Linux release 7.8.2003 (Core)
/usr/share/doc/pdns-backend-sqlite-4.4.1/schema.sqlite3.sql
```

**Comment by ju5t** [comment]
@LooOOooM I noticed the output of the rpm file too, but when you install the package, it doesn't seem to get copied to that location (tested on both CentOS 8 and CentOS 7 in Docker containers. Please test that too.

That would be a bug in the `pdns-backend-sqlite` package, but it does mean that this Puppet module will fail until you get that file and copy it yourself.

**Comment by LooOOooM** [comment]
@ju5t 
Nop, I cannot confirm that, as for me the Packages are there at least for version 4.4.1

```
[root@puppet-centos8-testvm1 ~]# cat /etc/redhat-release; rpm -ql pdns-backend-sqlite|grep \/schema; rpm -ql pdns-backend-sqlite|grep \/schema|xargs ls -l
CentOS Linux release 7.8.2003 (Core)
/usr/share/doc/pdns-backend-sqlite-4.4.1/schema.sqlite3.sql
-rw-r--r-- 1 root root 3043 Jan 12 21:56 /usr/share/doc/pdns-backend-sqlite-4.4.1/schema.sqlite3.sql
```
```
[root@puppet-centos8-testvm1 ~]# cat /etc/redhat-release; rpm -ql pdns-backend-sqlite|grep \/schema; rpm -ql pdns-backend-sqlite|grep \/schema|xargs ls -l
CentOS Linux release 8.2.2004 (Core)
/usr/share/doc/pdns-backend-sqlite/schema.sqlite3.sql
-rw-r--r-- 1 root root 3043 Jan 12 21:56 /usr/share/doc/pdns-backend-sqlite/schema.sqlite3.sql
```

**Comment by ju5t** [comment]
Sorry, not sure what happened the last few times I tested this (the files were definitely not there..) but in my latest try the files seem to be there.

**Pull request closed without merging**
