### PR TITLE
Allow empty value for security-poll-suffix

### PR DESCRIPTION
**Pull request by saz**
To disable any security polls, `security-poll-suffix` needs to be empty.

I'd also like to suggest to add a new paramter to `powerdns::config`, `empty_value_allowed`, instead of using a list of settings which might be empty

### CODE REVIEW

**Comment by ju5t** [comment]
Looks good, thanks for the contribution!

**Comment by regiohelden-dev** [comment]
@ju5t Thanks for merging. Any thoughts on my suggestion to solve this error once and for all?

**Comment by ju5t** [comment]
I'm a little lost. What suggestion do you mean?

If it's about @saz's comment on `empty_value_allowed` in the config, would that be a boolean that disables the check entirely or would it be a list that holds all the items that support empty values?

Personally I'm not a fan of either. I think we shouldn't allow too many changes on that part for the sake of stability.

**Comment by saz** [comment]
Sorry, I've sent https://github.com/sensson/puppet-powerdns/pull/88#issuecomment-770287969 using the wrong account. My bad.

`empty_value_allowed` should be a boolean. This way, you're making an explicit choice to add an empty value, which will disable the check of the value only.

Looking at the available settings, I think the list of 'empty string' values is lacking currently two settings. Maybe it's better to keep it as it is.

**Pull request merged**
