### PR TITLE
Convert to puppet 4+ data types

### PR DESCRIPTION
**Pull request by alexjfisher**
Also update some Gemfile versions now that puppet 3 (and older rubies)
aren't supported.

### CODE REVIEW

**Comment by alexjfisher** [comment]
I've been working on postgresql support. Those changes were getting a bit big for a single PR, so I'm pulling it apart to create smaller chunks of changes to review.

**Comment by ju5t** [comment]
@alexjfisher sounds like a plan. So far nothing out of the ordinary but the `Gemfile` needs a little adjustment so everything's in alphabetical order.

**Comment by ju5t** [comment]
Thanks!

**Comment by ju5t** [comment]
@alexjfisher sorry, I merged this to master by accident. Can you please open a new pull request to develop?

**Comment by alexjfisher** [comment]
My bad.  I'm pretty sure I branched off develop, but at the time the HEAD of develop and master were the same commit.  Then didn't pay attention when opening the PR.
Try https://github.com/sensson/puppet-powerdns/pull/26 and feel free to force push to master to permanently delete the stray commits if that works for you.  (I won't tell anyone! Promise! ;) )

**Comment by ju5t** [comment]
No problem. And I'm not too worried about those commits. It can stay as it is now. Thanks for all your work once again!

**Pull request merged**
