### PR TITLE
expand puppetlabs/stdlib dependency range to include 7.x

### LINKED ISSUE #105: support puppetlabs-stdlib 6.0.0 and higher
I wonder if it would be possible to support higher version of puppetlabs-stdlib.

many thanks,
hp

### PR DESCRIPTION
**Pull request by jackdpeterson**
Closes #105

### CODE REVIEW

**Comment by ju5t** [comment]
@jackdpeterson thanks! As your commit was pointed to the main branch (and not develop) I'm afraid tests didn't run. This is partly due to the little knowledge I have of the Github Actions system.

Just to confirm, did you run tests locally and if so, did all tests pass?

**Comment by saz** [comment]
@ju5t I've created #111 which will resolve a couple of PRs (including this one) and uses the develop branch.
Regarding Github Actions: is there any reason, that tests are only run for pull requests against develop? If not, I'm happy to send in a PR for a proper change.

**Comment by ju5t** [comment]
@saz not necessarily. I think eventually we might as well drop develop altogether and only have a main branch + tags. Which is good enough. Not testing on PR's to main is coming from what we used to do at our company.

**Comment by saz** [comment]
This issue has been resolved in develop with the merge of #111

**Comment by ju5t** [comment]
This got solved in #111.

@saz I will drop `develop` after it's released and tagged. After that, `main` will have all the latest code and we'll bump versions when things get released. This means we're pretty much ditching git flow (as we've used in the past).

**Comment by saz** [comment]
@ju5t See #112 for the github actions workflow change.

**Comment by ju5t** [comment]
@saz thanks! 2.1.2 was just released and I've dropped `develop` from this repo.

**Comment by saz** [comment]
@ju5t awesome! Thanks!

**Pull request closed without merging**
