### PR TITLE
allow to manage zones and records (with opt out) with puppet 

### PR DESCRIPTION
**Pull request by trefzer**
allow managing zones and records with puppet for a specific zone.
The service name change commit simplifies the autorequire dependencies.

### CODE REVIEW

**Comment by ju5t** [comment]
🤯 

I will try to free up some time to review this. Massive feature. Thanks so much for contributing.

**Comment by trefzer** [comment]
youre welcome.
if you like, I can make the first commit (use service name as a parameter) a separate merge request.
I now fixed/commented all rubocop mentions (I use pdk for my modules, which has a different .rubocop.yaml)

**Comment by ju5t** [comment]
@trefzer that's not necessary. The changelog is written by hand and I generally base it on what has been committed. I am going to try and go through it all this Monday so we can get this merged ASAP.

**Comment by trefzer** [comment]
Great, I will try to make checks happy over the weekend ! 
Currently I cannot reproduce them and I have no idea what this error is:
```
Error: Style/FetchEnvVar: Use `ENV.fetch('GEM_SOURCE')` or `ENV.fetch('GEM_SOURCE', nil)` instead of `ENV['GEM_SOURCE']`. (https://rubystyle.guide/#hash-fetch-defaults)`
```
Do you have an idea ? (I can also not figure out at which position the error occurs)

**Comment by trefzer** [comment]
Hm I think the error of the tests is in the Gemfile and not in my code ! The second pending merge request #121 has the same error !

**Comment by trefzer** [comment]
Yes !!! ;)
I made a separate request for the rubocop fix (#123). So you can merge it separately (a rebase on #120 will fix the error there as well).

**Comment by ju5t** [comment]
I think this is ready to roll!

**Comment by trefzer** [comment]
Thanks, but now you have been to fast ! I found a problem: there is case that can occur so puppet updates the zone each time. I'm just testing a patch that sorts the records, so this does not occur anymore....

**Comment by trefzer** [comment]
I think so, I did not find any issues anymore. And its running on production.

**Pull request merged**
