### PR TITLE
Convert to pdk

### PR DESCRIPTION
**Pull request by deric**
This PR changes too many files, it's a result of running

```
pdk convert
```
from module directory. By converting to [PDK](https://puppet.com/try-puppet/puppet-development-kit/) the module will follow best practices for Puppet modules. It will ensure compatibility with newer Ruby releases, e.g. 2.7 which is currently broken. Also you don't have to maintain Rubocop rules etc.

Running 
```
pdk update
```
would update module structure to the latest version. If you wish to update any files touched by PDK, it should be done in `.sync.yml` file.

### CODE REVIEW

**Comment by ju5t** [comment]
@deric I'm guessing this might need some changes in how we test/deploy this package to Forge?

**Comment by deric** [comment]
@ju5t Not necessarily, it looks like you're using [action-forge-publish](https://github.com/barnumbirr/) it [uses internally pdk](https://github.com/barnumbirr/action-forge-publish/blob/master/entrypoint.sh#L21):
```
pdk build
```
But of course, it should be carefully tested.

**Comment by ju5t** [comment]
@deric we don't have the capacity at the moment to test this thoroughly. Considering what has changed; I believe this would only affect our tests and wouldn't affect people using it, am I right?

**Comment by deric** [comment]
@ju5t Yes, it shouldn't affect people using the module. It takes care of boilerplate code and makes maintaining module easier.

**Pull request merged**
