### PR TITLE
.fixtures.yml: Migrate to git

### PR DESCRIPTION
**Pull request by bastelfreak**
it's best practice to use git branches in unit tests, not the latest forge releases. This approach tries to catch breaking changes or regressions in depenencies before they are released.

also contains:
* #154
* #156 
* #152 
* #153 
* #157 
* #158
* #155

### CODE REVIEW

**Comment by bastelfreak** [comment]
@ju5t this is the final PR. I tried to split up all changes in individual PRs so we get a proper changelog.

**Comment by ju5t** [comment]
I don't find this approach very developer friendly. If I make a PR to a module, I would like to start with green tests. With this change, it's not unlikely that our tests will fail because a third party module has introduced a breaking change or changed requirements. 

It could potentially lead to delayed releases too. We/contributors would have to implement fixes for all the breaking changes.

Personally, I wouldn't like that.

**Comment by ju5t** [comment]
I agree, testing against old versions makes no sense.

Would it be possible to pick the latest released version somehow, instead of the `main` branch? There can be many changes before a new version gets released and that's not always a good thing.

**Comment by ju5t** [comment]
We'll go the YOLO path for now. Thanks for the insane amount of work!

**Pull request merged**
