### PR TITLE
allow-notify-from may be empty too

### PR DESCRIPTION
**Pull request by marknl**

### CODE REVIEW

**Comment by alexjfisher** [comment]
@marknl I think you need to target the 'develop' branch with your PR.  That's where mine was recently merged to.

**Comment by alexjfisher** [comment]
I touch the same code in https://github.com/sensson/puppet-powerdns/pull/22/files#diff-0ac866172efd29d0ddc2aa75ae6f182dR9

**Comment by ju5t** [comment]
@marknl I've changed target of this merge request. Could you look at the conflicts @alexjfisher mentioned?

This will also make sure the tests in Travis will pass again as that was solved in #21.

I will make sure we'll release a new version of this module shortly after.

**Comment by marknl** [comment]
Fixed! Next time i'll use better branch names. ;)

**Comment by ju5t** [comment]
Awesome, thanks @marknl!

**Pull request merged**
