### PR TITLE
authoritative and recursor package should depend on apt repo, fixes #90

### LINKED ISSUE #90: Dependency cycle if apt repo is managed
Due to https://github.com/sensson/puppet-powerdns/blob/a3801785c09395642b5701ecd752b59bd396041c/manifests/repo.pp#L62 a run results in a dependency cycle, if you're using `apt::ppa` and the `package_manage => true` is set on `apt:ppa`:

```
Error: Found 1 dependency cycle:                                                                     
(Exec[add-apt-repository-ppa:ondrej/php] => Class[Apt::Update] => Exec[apt_update] => Class[Apt::Update] => Package[software-properties-common] => Exec[add-apt-repository-ppa:ondrej/php])\nTry the '--gra
ph' option and opening the resulting '.dot' file in OmniGraffle or GraphViz                          
Error: Failed to apply catalog: One or more resource dependency cycles detected in graph
```

If `package_manage` is set to `true`, the `software-properties-common` package will be installed, but this is now having a dependency on `Class['apt::update']`...

See https://github.com/puppetlabs/puppetlabs-apt/blob/8ab173b701246eae04611157057e787817cf3897/manifests/ppa.pp#L67 and https://github.com/puppetlabs/puppetlabs-apt/blob/8ab173b701246eae04611157057e787817cf3897/manifests/ppa.pp#L83-L91

### PR DESCRIPTION
**Pull request by saz**
Fixes #90

### CODE REVIEW

**Comment by ju5t** [comment]
Ah, I thought you were going for a different change. My bad.

I have no way to test this properly though. I did run a test with Beaker and it seems to be OK, but that's also because it's the first Puppet run and it would always update apt.

I trust this fixes it. Thanks!

**Comment by regiohelden-dev** [comment]
I've used the develop branch for a couple of tests and all are looking good.
A new release would be great, with those changes included.

**Comment by ju5t** [comment]
I will try to release a new version either today or later this week. During the week my time is always a bit limited.

<sup>Ps. it's not a problem, but it's a little bit confusing to see two different accounts here from the same person.</sup>

**Comment by ju5t** [comment]
@regiohelden-dev @saz I've just released 2.1.1. I did something wrong locally so 2.1.0 hasn't made it to the forge.

**Comment by saz** [comment]
Awesome! Thanks!

**Pull request merged**
