### PR TITLE
default path to sqlite scheme went more generic

### PR DESCRIPTION
**Pull request by LooOOooM**

### CODE REVIEW

**Comment by ju5t** [comment]
Not sure what you did, but you should've based your PR on on the develop branch. Anyway, I've changed it to so it gets merged into develop. Not sure why you didn't do that.

You've posted the below in #97.

```
# cat /etc/redhat-release
CentOS Linux release 7.9.2009 (Core)

# rpm -qa|grep pdns
pdns-backend-sqlite-4.5.0-0.alpha0.master.928.g2b3dbbb61.1pdns.el7.x86_64
pdns-recursor-4.5.0-0.alpha3.master.105.g2b3dbbb61.1pdns.el7.x86_64
pdns-4.5.0-0.alpha0.master.928.g2b3dbbb61.1pdns.el7.x86_64

#rpm -ql pdns-backend-sqlite-4.5.0-0.alpha0.master.928.g2b3dbbb61.1pdns.el7.x86_64|grep "\/schema.sqlite3.sql"
/usr/share/doc/pdns-backend-sqlite-4.5.0/schema.sqlite3.sql


# cat /etc/redhat-release
CentOS Linux release 8.2.2004 (Core)

# rpm -qa|grep pdns
pdns-backend-sqlite-4.5.0-0.alpha0.master.1020.g84808ff64.1pdns.el8.x86_64
pdns-recursor-4.5.0-0.beta1.master.11.g84808ff64.1pdns.el8.x86_64
pdns-4.5.0-0.alpha0.master.1020.g84808ff64.1pdns.el8.x86_64

#  rpm -ql pdns-backend-sqlite-4.5.0-0.alpha0.master.1020.g84808ff64.1pd
```

You're using an alpha package? I'm testing with the official PowerDNS repositories. Please explain.

**Comment by ju5t** [comment]
Also, please reword your commit so it references the correct issue.

**Comment by LooOOooM** [comment]
```
# cat /etc/yum.repos.d/powerDNS-*
[powerDNS-auth]
name=PowerDNS repository for PowerDNS Authoritative Server - master branch $releasever - $basearch
baseurl=http://repo.powerdns.com/centos/$basearch/$releasever/auth-master
enabled=1
gpgcheck=1
gpgkey=https://repo.powerdns.com/CBC8B383-pub.asc
includepkgs=pdns*
priority=50
[powerDNS-rec]
name=PowerDNS repository for PowerDNS Recursor - master branch
baseurl=http://repo.powerdns.com/centos/$basearch/$releasever/rec-master
enabled=1
gpgcheck=1
gpgkey=https://repo.powerdns.com/CBC8B383-pub.asc
includepkgs=pdns*
priority=50


# yum info pdns-backend-sqlite
PowerDNS repository for PowerDNS Authoritative Server - master branch 8 - x86_64                                                                                                                                    20 kB/s | 2.9 kB     00:00
PowerDNS repository for PowerDNS Authoritative Server - master branch 8 - x86_64                                                                                                                                   284 kB/s |  37 kB     00:00
PowerDNS repository for PowerDNS Recursor - master branch                                                                                                                                                           73 kB/s | 2.9 kB     00:00
Installed Packages
Name         : pdns-backend-sqlite
Version      : 4.5.0
Release      : 0.alpha0.master.1020.g84808ff64.1pdns.el8
Architecture : x86_64
Size         : 89 k
Source       : pdns-4.5.0-0.alpha0.master.1020.g84808ff64.1pdns.el8.src.rpm
Repository   : @System
From repo    : powerDNS-auth
Summary      : SQLite backend for pdns
URL          : https://powerdns.com
License      : GPLv2
Description  : This package contains the SQLite backend for pdns

Available Packages
Name         : pdns-backend-sqlite
Version      : 4.5.0
Release      : 0.alpha0.master.1023.gf5f513972.1pdns.el8
Architecture : x86_64
Size         : 28 k
Source       : pdns-4.5.0-0.alpha0.master.1023.gf5f513972.1pdns.el8.src.rpm
Repository   : powerDNS-auth
Summary      : SQLite backend for pdns
URL          : https://powerdns.com
License      : GPLv2
Description  : This package contains the SQLite backend for pdns
```

**Comment by ju5t** [comment]
Sorry mate but you've lost me. What am I supposed to get out such random comments? You can't just post the output of something, you have to explain what you mean.

You're very eager to get this feature pushed, but for some reason you're missing most of my comments and don't care at all about best practices. Please use https://www.conventionalcommits.org/en/v1.0.0/. Don't use random commit messages. Especially as you're referencing completely unrelated issues by adding an # and a number. We won't merge this unless you fix those commits.

Also, you're still not checking if the file exists. As I said, in my tests, the files are not copied. You can use `-ql` to list them, but they're not there. You're also still use a version that isn't officially released. Please base your changes on released versions only. We're not supporting beta or even alpha versions.

I do appreciate your contributions but please follow some standard guidelines and practices.

**Comment by LooOOooM** [comment]
[root@puppet-centos8-testvm1 ~]# cat /etc/yum.repos.d/
CentOS-Base.repo        CentOS-PowerTools.repo  CentOS-Updates.repo     EPEL.repo               ocsinventory.repo       powerDNS-auth.repo      powerDNS-rec.repo
[root@puppet-centos8-testvm1 ~]# cat /etc/yum.repos.d/powerDNS-*
[powerDNS-auth]
name=PowerDNS repository for PowerDNS Authoritative Server - master branch $releasever - $basearch
baseurl=http://repo.powerdns.com/centos/$basearch/$releasever/auth-master
enabled=1
gpgcheck=1
gpgkey=https://repo.powerdns.com/CBC8B383-pub.asc
includepkgs=pdns*
priority=50
[powerDNS-rec]
name=PowerDNS repository for PowerDNS Recursor - master branch
baseurl=http://repo.powerdns.com/centos/$basearch/$releasever/rec-master
enabled=1
gpgcheck=1
gpgkey=https://repo.powerdns.com/CBC8B383-pub.asc
includepkgs=pdns*
priority=50
[root@puppet-centos8-testvm1 ~]# yum info pdns-backend-sqlite
PowerDNS repository for PowerDNS Authoritative Server - master branch 8 - x86_64                                                                                                                                    20 kB/s | 2.9 kB     00:00
PowerDNS repository for PowerDNS Authoritative Server - master branch 8 - x86_64                                                                                                                                   284 kB/s |  37 kB     00:00
PowerDNS repository for PowerDNS Recursor - master branch                                                                                                                                                           73 kB/s | 2.9 kB     00:00
Installed Packages
Name         : pdns-backend-sqlite
Version      : 4.5.0
Release      : 0.alpha0.master.1020.g84808ff64.1pdns.el8
Architecture : x86_64
Size         : 89 k
Source       : pdns-4.5.0-0.alpha0.master.1020.g84808ff64.1pdns.el8.src.rpm
Repository   : @System
From repo    : powerDNS-auth
Summary      : SQLite backend for pdns
URL          : https://powerdns.com
License      : GPLv2
Description  : This package contains the SQLite backend for pdns

Available Packages
Name         : pdns-backend-sqlite
Version      : 4.5.0
Release      : 0.alpha0.master.1023.gf5f513972.1pdns.el8
Architecture : x86_64
Size         : 28 k
Source       : pdns-4.5.0-0.alpha0.master.1023.gf5f513972.1pdns.el8.src.rpm
Repository   : powerDNS-auth
Summary      : SQLite backend for pdns
URL          : https://powerdns.com
License      : GPLv2
Description  : This package contains the SQLite backend for pdns

**Comment by ju5t** [comment]
@LooOOooM gotcha. In that case we'll revert the fix in develop too as we'd like a more sturdy fix. We'd still accept that if you're up for it but if not, that's fine too.

If you do open PR's in the future, either with ourselves or others, please try to follow some guidelines. If you can't, don't open a PR either.

Have a good day.

**Pull request closed without merging**
