### PR TITLE
update dependencies

### PR DESCRIPTION
**Pull request by saz**
This PR updates all dependencies and will resolve #109, #108, #107, #106, #105

### CODE REVIEW

**Comment by saz** [comment]
@ju5t I think those failing tests are a result of https://github.com/sensson/puppet-powerdns/blob/2d06eed8370d3465fe2e801f13d6ff932749a318/spec/classes/powerdns_init_spec.rb#L56
For me, it looks like as if *all* tests (including unrelated ones like the ones for `runit`) are executed.

**Comment by ju5t** [comment]
@saz Ruby is well passed my comfort zone to be honest.

Do you mean it runs tests that it shouldn't run? For example, those of external dependencies?

**Comment by saz** [comment]
It looks like that to me. I'd just drop the line. Your module isn't using runit at all and the test is located within puppet, which isn't part of your module :-)

**Comment by saz** [comment]
@ju5t I've added my suggested fix to this PR, now all tests are green

**Comment by ju5t** [comment]
@saz thanks!

**Pull request merged**
