### PR TITLE
Update MySQL and EPEL Versions

### PR DESCRIPTION
**Pull request by kvedder-amplex**

### CODE REVIEW

**Comment by kvedder-amplex** [comment]
Ok, this should resolve the previous conflicts, finally. Requesting a review and merge.

**Comment by kvedder-amplex** [comment]
I see the CI tests failed. Need me to fix something?

**Comment by ju5t** [comment]
If you know how to fix it, that would be great!

**Comment by saz** [comment]
@ju5t Can't see the logs right now, but Puppet 6 is EOL and a lot of things started to fail. I'd suggest to drop any tests related to Puppet 6

**Comment by ju5t** [comment]
@saz version 6 has been dropped in the latest version. 

As this PR has been open for a while and is based on an older version of this module, I think it's easier to create a new PR based of the current main branch and PR to that. Either that or rebase this PR so it's up to speed with the current branch.

**Comment by saz** [comment]
@ju5t I've created https://github.com/sensson/puppet-powerdns/pull/150 which updates all dependencies

**Comment by ju5t** [comment]
Closing this. See #150

**Pull request closed without merging**
